export const CREATE_BOOK_REQUEST = 'CREATE_BOOK_REQUEST';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_FAIL = 'CREATE_BOOK_FAIL';

export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';

export const PATCH_BOOK_REQUEST = 'PATCH_BOOK_REQUEST';
export const PATCH_BOOK_SUCCESS = 'PATCH_BOOK_SUCCESS';
export const PATCH_BOOK_FAIL = 'PATCH_BOOK_FAIL';
