export const CREATE_GOAL_REQUEST = 'CREATE_GOAL_REQUEST';
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS';
export const CREATE_GOAL_FAIL = 'CREATE_GOAL_FAIL';

export const GET_GOALS_REQUEST = 'GET_GOALS_REQUEST';
export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS';
export const GET_GOALS_FAIL = 'GET_GOALS_FAIL';

export const UPDATE_GOAL_REQUEST = 'UPDATE_GOAL_REQUEST';
export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const UPDATE_GOAL_FAIL = 'UPDATE_GOAL_FAIL';

export const DELETE_GOAL_REQUEST = 'DELETE_GOAL_REQUEST';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAIL = 'DELETE_GOAL_FAIL';
